nzo_url_encryptor:
    secret_key: 2dSksmNW2YgFmHlbN4ZVcNxr2CR3iVFo    # Required, max length of 100 characters.
    secret_iv: pXTGUT4M5zkUg5Ukw6pA4nwjy8EpGk6Y     # Required only if "random_pseudo_bytes" is FALSE. Max length of 100 characters.
#    cipher_algorithm:                      # optional, default: 'aes-256-ctr'
#    base64_encode:                         # optional, default: TRUE
#    format_base64_output:                  # optional, default: TRUE, used only when 'base64_encode' is set to TRUE
#    random_pseudo_bytes:                   # optional, default: FALSE (generate a random encrypted text output)